### ISSUE TITLE
Prefer self-hosted assets

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#813]
## What is the enhancement to be made?
Don't pull remote assets (fonts, css). Prefer self-hosted.

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)
Make it easier to host our docs offline

**Comment by michael-wisely-gravwell** [comment]
This is a pretty simple lift, as far as code goes. Looks like we only use two external resources, and they're both fonts. If anyone's aware of other external resources, please comment them on this issue.

The problem is that one of the fonts is an Adobe font (Erbaum), and I'm not sure that we're allowed to distribute it: https://use.typekit.net/gel7sic.css

Typekit has Terms of Use, and the font itself has a license that I'm unfamiliar with.

The other font is an Open Font License font (Lato). As I understand it, we can distribute that one.

SO:

We need to decide:

1. Do we care that the self-hosted, no-internet docs don't have the same fonts? Is it that big of a deal?
2. If we _do_ care to pack fonts, what do we do about the Adobe font?
