### ISSUE TITLE
Ingesters: Prefer section nav to list

### ISSUE THREAD

**Issue by michael-wisely-gravwell** [gravwell/wiki#871]
## What is the enhancement to be made?

Improve ingester discoverability by listing ingesters in a section nav on the left.

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

If I'm looking at the documentation for a search module, I can easily hop between different search modules. Extracion modules, processing modules, render modules... they're all at my fingertips in the [section navigation on the left](https://github.com/gravwell/wiki/assets/108433848/94dd2400-9f8e-4ca8-ba89-723e69fa79dc).

For ingesters, this is not the case.

If I'm looking at an ingester, [there is no section navigation](https://github.com/gravwell/wiki/assets/108433848/17bcfb87-e2e1-41f2-9491-846bf0ca2b5d).

Instead of hopping around the section navigation in the left nav, I have to either:

- know what ingester I'm searching for and search for it
- return to the Ingesters page and [look at the list that's there](https://github.com/gravwell/wiki/assets/108433848/16e86115-b80c-4554-b7c3-b4f802b923d2).

Listing ingesters on the left nav can help a lot with discoverability. Make it easy for the user to hop between ingesters to learn what Gravwell can do.

## Any other comments?

We can still keep the list. However, I still think the section nav would be a really nice add.

**Comment by ashnwade** [comment]
There is a `hidden: true` directive on the toctree for some of the lists. Before, the hidden directive would hide the list from the content section, but would still include the list in the primary sidebar navigation. Now the hidden directive hides it in both places. We chose to use this directive in multiple places because we prefer to show the list in a table with a description next to it. 

I was able to diagnose the problem, but I wasn't sure what the best way was to resolve it. 
It looks like there is an `includehidden` option for the toctree, but I didn't get it to behave the way I expected. It might be something to look into?

I also saw this source code for pydata-sphinx-theme: https://pydata-sphinx-theme.readthedocs.io/en/stable/_modules/pydata_sphinx_theme/toctree.html#

and I saw that there is a PR that may be related: `https://github.com/pydata/pydata-sphinx-theme/pull/1642`
